title: James M. Stanton
description: (312) 631-9949
theme: minima
author: 
name: James Stanton
email: "stantjm@gmail.com"
collections:
  artifacts:
    output: true


defaults:
  - scope:
      type: "artifacts"
    values:
      layout: artifact


