title: James M. Stanton's MLIS Graduate Portfolio
theme: minima
collections:
  collection:
    output: true


defaults:
  - scope:
      type: "collection"
    values:
      layout: collection_item

header_pages:
  - contents.md
  - essay.md
  - resume.md
  - evidence.md
  
