title: James M. Stanton
description: (312) 631-9949
theme: minima
author: James Stanton
name: James Stanton
collections:
  artifacts:
    output: true


defaults:
  - scope:
      type: "artifacts"
    values:
      layout: artifact


