title: James M. Stanton
description: (312) 631-9949
author: James Stanton
theme: minima
collections:
  artifacts:
    output: true


defaults:
  - scope:
      type: "artifacts"
    values:
      layout: artifact


